using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DependencyInjection.SourceGenerator.Microsoft.Helpers;
internal static class Trivia
{
    internal static AttributeListSyntax CreateExcludeFromCodeCoverage()
    {
        return SyntaxFactory.AttributeList(
                SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(
                        SyntaxFactory.QualifiedName(
                            SyntaxFactory.QualifiedName(
                                SyntaxFactory.QualifiedName(
                                    SyntaxFactory.AliasQualifiedName(
                                        SyntaxFactory.IdentifierName(
                                            SyntaxFactory.Token(SyntaxKind.GlobalKeyword)),
                                        SyntaxFactory.IdentifierName("System")),
                                    SyntaxFactory.IdentifierName("Diagnostics")),
                                SyntaxFactory.IdentifierName("CodeAnalysis")),
                            SyntaxFactory.IdentifierName("ExcludeFromCodeCoverage")))));
    }

    internal static SyntaxTriviaList CreateHeaderTrivia()
    {
        return SyntaxFactory.TriviaList(
            SyntaxFactory.Comment("// <auto-generated/>"),
            SyntaxFactory.Trivia(
                SyntaxFactory.PragmaWarningDirectiveTrivia(
                    SyntaxFactory.Token(SyntaxKind.DisableKeyword),
                    true)),
            SyntaxFactory.Trivia(
                SyntaxFactory.NullableDirectiveTrivia(
                    SyntaxFactory.Token(SyntaxKind.EnableKeyword),
                    true)));
    }

    internal static SyntaxToken CreateTrivia()
    {
        return SyntaxFactory.Token(
            CreateHeaderTrivia(),
            SyntaxKind.NamespaceKeyword,
            SyntaxFactory.TriviaList());
    }

    internal static CompilationUnitSyntax CreateCompilationUnitSyntax(
        ClassDeclarationSyntax classDeclaration,
        string @namespace,
        UsingDirectiveSyntax[]? usings = null,
        IEnumerable<MemberDeclarationSyntax>? additionalMembers = null)
    {
        // var excludeFromCodeCoverageSyntax = CreateExcludeFromCodeCoverage();
        // classDeclaration = classDeclaration.AddAttributeLists(excludeFromCodeCoverageSyntax);

        var trivia = Trivia.CreateTrivia();
        var namespaceDeclaration = SyntaxFactory.FileScopedNamespaceDeclaration(SyntaxFactory.IdentifierName(@namespace))
                .WithNamespaceKeyword(trivia);

        if (usings is not null)
            namespaceDeclaration = namespaceDeclaration.AddUsings(usings);

        namespaceDeclaration = namespaceDeclaration.AddMembers(classDeclaration);

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .AddMembers(namespaceDeclaration);

        if (additionalMembers is not null)
        {
            compilationUnit = compilationUnit.AddMembers(additionalMembers.ToArray());
        }

        return compilationUnit.NormalizeWhitespace();
    }
}
